---
volumes:
  keys-data:
    labels:
      net.mafro.kopia: true
  1pass-data: {}

services:
  salt-master:
    image: ghcr.io/cdalvaro/docker-salt-master:${SALT_MASTER_VERSION}
    restart: unless-stopped
    ports:
      - 4505:4505
      - 4506:4506
    environment:
      - TIMEZONE=Australia/Melbourne
      - SALT_LOG_LEVEL
      - SALT_LOG_ROTATE_FREQUENCY=weekly
      - SALT_LOG_ROTATE_RETENTION=4
      - PYTHON_PACKAGES=onepasswordconnectsdk==${_1PASSWORD_CONNECT_SDK_VERSION}
    volumes:
      - /home/mafro/dotfiles/salt:/home/salt/data/srv/salt:ro
      - /home/mafro/dotfiles/salt/pillar:/home/salt/data/srv/pillar:ro
      - keys-data:/home/salt/data/keys
      - ./logs:/home/salt/data/logs
      - ./config:/home/salt/data/config
      - ./1password-connect/salt:/var/cache/salt/master/extmods
    extra_hosts:
      locke: 192.168.1.198
    depends_on:
      - 1password-api

  1password-api:
    extends:
      file: 1password-connect/docker-compose.yml
      service: api
    depends_on:
      - 1password-sync

  1password-sync:
    extends:
      file: 1password-connect/docker-compose.yml
      service: sync
